### ISSUE TITLE
Secreto encontrado en código (SECRET_KEY)

### ISSUE THREAD

**Issue by cybercamphackathon** [scylla-waf/Scylla#2]
Se ha encontrado un secreto en el código que debería usarse desde un fichero de configuración, o en el caso de ser de test o desarrollo local, debería estar indicado en `README` o documentación/wiki:
```
# SECURITY WARNING: keep the secret key used in production secret!
23:SECRET_KEY = '1al4$$8ksmrq-qck@w-prt4dal!jm18%k+zkxzdu))xsy1_2i&'
```
Será necesaria también la rotación de dicho secreto, en el caso de estar en uso.

https://github.com/scylla-waf/Scylla/blob/master/scylla_dependencies/HTTPServer/scylla/scylla/settings.py#L23

**Comment by scylla-waf** [comment]
Ahora se lee desde scylla.conf, teniendo la opción de configurarlo desde la interfaz web.

**Comment by scylla-waf** [comment]
Añadida generación de claves automática con get_random_secret_key() ( en "commit random SECRET_KEY, key in scylla.conf"), el cual daba error cuando generaba "#", solucionado en commit "fixef key gen"
